### ISSUE TITLE
Required fields in quick forms

### ISSUE THREAD

**Issue by paul121** [mstenta/farm_pcsc#10]
What fields need to be required in quick forms? Should any fields not be required?

eg:

Farm/Field Summary:
- Presumably one value each for "Producer received 1/2/3", "Incentive Reason 1/2/3", "Incentive Structure 1/2/3" will be required?
- Likely require some of the numeric/cost fields? eg: Implementation cost

**Comment by mstenta** [comment]
Let's see what feedback we get from TAPs as they start using it, and make adjustments as we go.
