### ISSUE TITLE
Add more action buttons to quick forms

### ISSUE THREAD

**Issue by mstenta** [mstenta/farm_pcsc#15]
The TAP role does not currently have access to the Quick Forms index, which means they can't get to the quick forms unless we link to them from other places in the UI. Some Views have a link in their empty text, but this is only visible until a record is added. It's then impossible to add another. We should add more action buttons in appropriate places to make this easier. We can also consider granting access to the Quick Forms index, but I think action buttons should be done either way, since they are more contextual.

- "Add Practice" on field enrollment records
- "Add Commodity" on field enrollment records
- ...

**Comment by paul121** [comment]
I've added more action buttons that link to quick forms:
- Plan pages have Field enrollment, Farm summary and Field summary.
- *All* plan record pages have Practice and Commodity actions. It's not easy to limit which bundles these display on but it's a good start for now.

I also added button links in the views table headers for all of the quick forms. So there will either be an empty table + a quick form link OR a header button/link to the quick form.
![Screenshot from 2024-05-31 15-27-21](https://github.com/mstenta/farm_pcsc/assets/3116995/0347b9f3-a512-4c7e-9b84-0f282043a67e)
