### ISSUE TITLE
Impossible to change state and county in entity forms

### ISSUE THREAD

**Issue by mstenta** [mstenta/farm_pcsc#17]
There is currently a bug with entity edit forms that include State and County fields. The County field only shows options that are relevant to the selected State. However, there is no ajax logic to reload the County options when the State changes (there is in the quick forms, but not in the entity forms). This means it's impossible to change the state/county.

I started working on a fix for this in a `1.x-state-county-reload` branch, but didn't finish it. The ajax wasn't working correctly, but it's a start.

This is definitely a bug, but maybe isn't urgent because in practice these won't be changing once they are created.

**Comment by paul121** [comment]
Done

Needed to set the wrapper ID and process the `pcsc_county` form state value to work with a submitted array.
