### ISSUE TITLE
Support new Project Structure sheet

### ISSUE THREAD

**Issue by paul121** [mstenta/farm_pcsc#27]
Instructions: These data will be collected at the project level. The data describe the methods the project uses to engage producers and establish climate benefits. Each unique set of outreach, assistance, incentive, and MMRV approaches will correspond to one project structure. If the project uses multiple project structures, an additional row should be filled out for each unique combination of variables describing an approach. Complete the worksheet at the initiation of the project and update in any quarters that the project offers a new or revised project structure.

**Comment by paul121** [comment]
It seems that this sheet is mostly moving the "incentive structure 1/2/3/4" questions from the farm summary to a new sheet. Because these structures are more consistent and won't change throughout the project

**Comment by vicspinfox** [comment]
Additional notes from training call 6/27: 
* This sheet is designed to show results & impacts & correlate them with different methods 
* Include a row for each commodity x approach - if the approach is commodity specific, (i,e one incentive for corn only) include the commodity - if not, leave it out

**Comment by mstenta** [comment]
I'm wondering: do we need to collect this in the farmOS module at all? Or is this always going to be high-level and never really changing? I don't think this requires rows per-producer, so I'm not sure there's anything for a normal TAP to fill out, unless I'm mistaken. Maybe this is just filled out once at the highest level, per-commodity, just to inform the USDA how OpenTEAM in general is approaching each commodity type?

So maybe this is outside the scope of the farmOS module?

**Comment by mstenta** [comment]
We talked about this with Vic and it sounds like it will be filled in manually. We can reopen in the future if that changes.
