### ISSUE TITLE
Allowed values should be defined as associative arrays

### ISSUE THREAD

**Issue by paul121** [mstenta/farm_pcsc#3]
https://github.com/mstenta/farm_pcsc/blob/beb27e5943c52cfb19cfa13b0c4ba96176b88816/src/Plugin/PlanRecord/PlanRecordType/PcscFieldPractice327.php#L35-L41

The allowed values arrays should be associative arrays, in this PCSC case with matching keys and values. As implemented we store a numeric (maybe a string?) integer in the database for these fields. When exporting this data we would get integrers and it wouldn't be clear what the values actually are.

There are many instances of this. Other than just `array_combine($values, $values)` it might be nice to make a little helper function to build the associative arrays ? I feel like Drupal has a helper for building `#options` values but I couldn't find it.

**Comment by mstenta** [comment]
Fixed with a simple helper function. If we want to improve on that in the future we can, but this resolves the issue. Thanks for flagging that @paul121!
